### ISSUE TITLE
Rubygem doesn't contain license information

### ISSUE THREAD

**Issue by sethwoodworth** [jnicklas/xpath#71]
https://rubygems.org/gems/xpath/versions/2.0.0

When I ran a [license checker](https://github.com/pivotal/LicenseFinder) against my Gemfile, your xpath was the only one without a license listed.  As is clear from your README, xpath is MIT licensed.  It appears that rubygems needs to be told this.

**Comment by jtrees** [comment]
We also just encountered this issue. It might suffice to add a `LICENCE.txt` file.

**Comment by andrewdavidmackenzie** [comment]
Yes, add a LICENCE file, and also specify the license name in the gemspec.

Then the license should show in github (they now display it in the top-bar of a project), it should show in rubygems.org and then can also be detected by license_finder gem.

thanks!

**Comment by jnicklas** [comment]
This is now fixed.
